spring:
 profiles:
  active: common

server:
 port: 9090		
---
spring:
 profiles: common
 jpa:
  properties:
   hibernate:
    dialect: org.hibernate.dialect.MySQL5Dialect
  hibernate:
   ddl-auto: create
 datasource:
  url: jdbc:mysql://localhost:3306/StuMgmt
  username: root
  password: Qasource@123
  driver-class-name: com.mysql.cj.jdbc.Driver
  test-while-idle: true
  time-between-eviction-runs-millis: 60000
  validation-query: SELECT 1
#Logging Properties	
logging: 
 pattern:
  console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
 level:
  org:
   hibernate:
    SQL: debug
---